import type { DraGermaniaPublicWebsiteContentNode } from "./dra-germania-public-website-content-types.ts"
import { draGermaniaPublicWebsiteNotionSourceRefs } from "./dra-germania-public-website-content-types.ts"

const strategicRefs = [
  draGermaniaPublicWebsiteNotionSourceRefs.phase06,
  draGermaniaPublicWebsiteNotionSourceRefs.phase07,
  draGermaniaPublicWebsiteNotionSourceRefs.phase08,
  draGermaniaPublicWebsiteNotionSourceRefs.phase09,
  draGermaniaPublicWebsiteNotionSourceRefs.phase10,
  draGermaniaPublicWebsiteNotionSourceRefs.phase11,
]

const structuralRefs = [
  draGermaniaPublicWebsiteNotionSourceRefs.main,
  draGermaniaPublicWebsiteNotionSourceRefs.phase10,
  draGermaniaPublicWebsiteNotionSourceRefs.phase11,
]

const holdRefs = [
  draGermaniaPublicWebsiteNotionSourceRefs.phase06,
  draGermaniaPublicWebsiteNotionSourceRefs.phase08,
  draGermaniaPublicWebsiteNotionSourceRefs.phase10,
  draGermaniaPublicWebsiteNotionSourceRefs.phase11,
]

/** Nós de conteúdo do site público da Dra. Germânia (Semantic Content Map completo). */
export const draGermaniaPublicWebsiteContentNodes = [
  { page_id: "page_home", content_node_id: "home", silo_id: null, hub_id: null, page_type: "home", internal_title: "Home", canonical_topic: "Homepage publica cinematografica da Dra. Germania Bandeira", slug: "/", parent: null, primary_intent: "narrative_conversion", supporting_intents: ["brand_trust", "semantic_navigation"], priority: "P0", publication_status: "draft", indexability: "not_public", must_link_to: ["hub_emagrecimento_obesidade", "hub_composicao_corporal", "hub_saude_metabolica", "agendamento"], should_receive_links_from: [], do_not_compete_with: ["landing_discovery"], conversion_goal: "appointment_start", cta_id: "cta_home_agendamento", schema_type: "WebPage", credential_status: "pending_verification", review_status: "draft", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: structuralRefs },
  { page_id: "page_sobre", content_node_id: "sobre", silo_id: null, hub_id: null, page_type: "institutional", internal_title: "Sobre", canonical_topic: "Identidade profissional verificavel da Dra. Germania Bandeira", slug: "/sobre/", parent: "home", primary_intent: "institutional_trust", supporting_intents: ["credential_validation"], priority: "P0", publication_status: "draft", indexability: "not_public", must_link_to: ["agendamento", "politica_editorial"], should_receive_links_from: ["home"], do_not_compete_with: ["hold_nutrologia_titulo_landing"], conversion_goal: "appointment_start", cta_id: "cta_sobre_agendamento", schema_type: "AboutPage", credential_status: "pending_verification", review_status: "draft", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: structuralRefs },
  { page_id: "page_agendamento", content_node_id: "agendamento", silo_id: null, hub_id: null, page_type: "conversion", internal_title: "Agendamento", canonical_topic: "Fluxo de agendamento e expectativa de atendimento", slug: "/agendamento/", parent: "home", primary_intent: "conversion", supporting_intents: ["appointment_expectation", "contact"], priority: "P0", publication_status: "draft", indexability: "not_public", must_link_to: ["privacidade"], should_receive_links_from: ["home", "hub_emagrecimento_obesidade", "hub_composicao_corporal", "hub_saude_metabolica"], do_not_compete_with: ["local_joao_pessoa", "local_campina_grande"], conversion_goal: "appointment_completed", cta_id: "cta_agendamento_submit", schema_type: "ContactPage", credential_status: "pending_verification", review_status: "draft", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: structuralRefs },
  { page_id: "page_politica_editorial", content_node_id: "politica_editorial", silo_id: null, hub_id: null, page_type: "legal", internal_title: "Politica Editorial", canonical_topic: "Politica editorial e governanca de conteudo medico", slug: "/politica-editorial/", parent: "home", primary_intent: "editorial_governance", supporting_intents: ["ymyl_transparency", "review_policy"], priority: "P0", publication_status: "draft", indexability: "not_public", must_link_to: ["privacidade"], should_receive_links_from: ["home", "sobre"], do_not_compete_with: [], conversion_goal: null, cta_id: null, schema_type: "WebPage", credential_status: "not_applicable", review_status: "draft", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: structuralRefs },
  { page_id: "page_privacidade", content_node_id: "privacidade", silo_id: null, hub_id: null, page_type: "legal", internal_title: "Privacidade", canonical_topic: "Privacidade e LGPD", slug: "/privacidade/", parent: "home", primary_intent: "legal_privacy", supporting_intents: ["lgpd", "data_rights"], priority: "P0", publication_status: "draft", indexability: "not_public", must_link_to: [], should_receive_links_from: ["home", "agendamento", "politica_editorial"], do_not_compete_with: [], conversion_goal: null, cta_id: null, schema_type: "WebPage", credential_status: "not_applicable", review_status: "draft", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: structuralRefs },
  { page_id: "page_hub_emagrecimento_obesidade", content_node_id: "hub_emagrecimento_obesidade", silo_id: "silo_emagrecimento_obesidade", hub_id: "hub_emagrecimento_obesidade", page_type: "hub", internal_title: "Emagrecimento / Obesidade", canonical_topic: "Emagrecimento clinico e obesidade sem solucao unica", slug: "/emagrecimento-obesidade/", parent: "home", primary_intent: "informational_investigational_commercial", supporting_intents: ["weight_loss_difficulty", "obesity_context", "maintenance"], priority: "P0", publication_status: "draft", indexability: "not_public", must_link_to: ["hub_composicao_corporal", "hub_saude_metabolica", "agendamento"], should_receive_links_from: ["home", "spoke_por_que_nao_consigo_emagrecer", "spoke_reganho_manutencao"], do_not_compete_with: ["hold_nutrologia_titulo_landing", "local_joao_pessoa", "local_campina_grande"], conversion_goal: "appointment_start", cta_id: "cta_hub_emagrecimento_agendamento", schema_type: "MedicalWebPage", credential_status: "pending_verification", review_status: "review_required", medical_review_status: "pending", regulatory_check_status: "pending", source_refs: strategicRefs },
  { page_id: "page_hub_composicao_corporal", content_node_id: "hub_composicao_corporal", silo_id: "silo_composicao_corporal", hub_id: "hub_composicao_corporal", page_type: "hub", internal_title: "Composicao Corporal", canonical_topic: "Composicao corporal e preservacao muscular alem da balanca", slug: "/composicao-corporal/", parent: "home", primary_intent: "informational_commercial", supporting_intents: ["body_composition", "muscle_preservation", "bioimpedance_context"], priority: "P0", publication_status: "draft", indexability: "not_public", must_link_to: ["hub_emagrecimento_obesidade", "hub_saude_metabolica", "agendamento"], should_receive_links_from: ["home", "spoke_preservacao_muscular", "spoke_bioimpedancia", "context_menopausa_composicao_metabolismo"], do_not_compete_with: ["hold_suplementacao_hub"], conversion_goal: "appointment_start", cta_id: "cta_hub_composicao_agendamento", schema_type: "MedicalWebPage", credential_status: "pending_verification", review_status: "review_required", medical_review_status: "pending", regulatory_check_status: "pending", source_refs: strategicRefs },
  { page_id: "page_hub_saude_metabolica", content_node_id: "hub_saude_metabolica", silo_id: "silo_saude_metabolica", hub_id: "hub_saude_metabolica", page_type: "hub", internal_title: "Saude Metabolica", canonical_topic: "Saude metabolica como contexto clinico do peso e composicao corporal", slug: "/saude-metabolica/", parent: "home", primary_intent: "informational_commercial", supporting_intents: ["metabolic_health", "insulin_resistance", "clinical_context"], priority: "P0", publication_status: "draft", indexability: "not_public", must_link_to: ["hub_emagrecimento_obesidade", "hub_composicao_corporal", "agendamento"], should_receive_links_from: ["home", "spoke_resistencia_insulina", "context_menopausa_composicao_metabolismo"], do_not_compete_with: ["hold_saude_hormonal_generica", "metabolismo_lento_isolado"], conversion_goal: "appointment_start", cta_id: "cta_hub_saude_metabolica_agendamento", schema_type: "MedicalWebPage", credential_status: "pending_verification", review_status: "review_required", medical_review_status: "pending", regulatory_check_status: "pending", source_refs: strategicRefs },
  { page_id: "page_por_que_nao_consigo_emagrecer", content_node_id: "spoke_por_que_nao_consigo_emagrecer", silo_id: "silo_emagrecimento_obesidade", hub_id: "hub_emagrecimento_obesidade", page_type: "spoke", internal_title: "Por que nao consigo emagrecer?", canonical_topic: "Dificuldade para emagrecer sem diagnostico remoto ou causa unica", slug: "/emagrecimento-obesidade/por-que-nao-consigo-emagrecer/", parent: "hub_emagrecimento_obesidade", primary_intent: "informational", supporting_intents: ["metabolic_context", "clinical_assessment", "longitudinal_follow_up"], priority: "P0", publication_status: "draft", indexability: "not_public", must_link_to: ["hub_emagrecimento_obesidade", "hub_saude_metabolica", "agendamento"], should_receive_links_from: ["hub_emagrecimento_obesidade", "home"], do_not_compete_with: ["metabolismo_lento_isolado"], conversion_goal: "appointment_start", cta_id: "cta_spoke_dificuldade_agendamento", schema_type: "Article", credential_status: "pending_verification", review_status: "review_required", medical_review_status: "pending", regulatory_check_status: "pending", source_refs: strategicRefs },
  { page_id: "page_reganho_manutencao", content_node_id: "spoke_reganho_manutencao", silo_id: "silo_emagrecimento_obesidade", hub_id: "hub_emagrecimento_obesidade", page_type: "spoke", internal_title: "Reganho e manutencao", canonical_topic: "Reganho de peso, efeito sanfona e manutencao como tema consolidado", slug: "/emagrecimento-obesidade/reganho-manutencao/", parent: "hub_emagrecimento_obesidade", primary_intent: "informational", supporting_intents: ["weight_regain", "maintenance", "follow_up_adjustment"], priority: "P0", publication_status: "draft", indexability: "not_public", must_link_to: ["hub_emagrecimento_obesidade", "agendamento"], should_receive_links_from: ["hub_emagrecimento_obesidade", "context_farmacoterapia_glp1"], do_not_compete_with: ["efeito_sanfona_separado", "manutencao_separada"], conversion_goal: "appointment_start", cta_id: "cta_spoke_reganho_agendamento", schema_type: "Article", credential_status: "pending_verification", review_status: "review_required", medical_review_status: "pending", regulatory_check_status: "pending", source_refs: strategicRefs },
  { page_id: "page_preservacao_muscular", content_node_id: "spoke_preservacao_muscular", silo_id: "silo_composicao_corporal", hub_id: "hub_composicao_corporal", page_type: "spoke", internal_title: "Preservacao muscular no emagrecimento", canonical_topic: "Preservacao de massa muscular durante o emagrecimento", slug: "/composicao-corporal/preservacao-muscular-no-emagrecimento/", parent: "hub_composicao_corporal", primary_intent: "investigational", supporting_intents: ["muscle_mass", "quality_of_weight_loss", "body_composition"], priority: "P0", publication_status: "draft", indexability: "not_public", must_link_to: ["hub_composicao_corporal", "hub_emagrecimento_obesidade", "agendamento"], should_receive_links_from: ["hub_composicao_corporal", "context_farmacoterapia_glp1"], do_not_compete_with: ["emagrecimento_sem_massa_muscular_duplicado", "hold_suplementacao_hub"], conversion_goal: "appointment_start", cta_id: "cta_spoke_preservacao_agendamento", schema_type: "Article", credential_status: "pending_verification", review_status: "review_required", medical_review_status: "pending", regulatory_check_status: "pending", source_refs: strategicRefs },
  { page_id: "page_bioimpedancia", content_node_id: "spoke_bioimpedancia", silo_id: "silo_composicao_corporal", hub_id: "hub_composicao_corporal", page_type: "spoke", internal_title: "Bioimpedancia", canonical_topic: "Bioimpedancia como instrumento de acompanhamento com limites", slug: "/composicao-corporal/bioimpedancia/", parent: "hub_composicao_corporal", primary_intent: "informational", supporting_intents: ["body_composition_measurement", "interpretation_limits"], priority: "P0", publication_status: "draft", indexability: "not_public", must_link_to: ["hub_composicao_corporal", "agendamento"], should_receive_links_from: ["hub_composicao_corporal"], do_not_compete_with: ["bioimpedancia_preco_separada", "bioimpedancia_joao_pessoa"], conversion_goal: "appointment_start", cta_id: "cta_spoke_bioimpedancia_agendamento", schema_type: "Article", credential_status: "pending_verification", review_status: "review_required", medical_review_status: "pending", regulatory_check_status: "pending", source_refs: strategicRefs },
  { page_id: "page_resistencia_insulina", content_node_id: "spoke_resistencia_insulina", silo_id: "silo_saude_metabolica", hub_id: "hub_saude_metabolica", page_type: "spoke", internal_title: "Resistencia a insulina", canonical_topic: "Resistencia a insulina em contexto de saude metabolica", slug: "/saude-metabolica/resistencia-a-insulina/", parent: "hub_saude_metabolica", primary_intent: "informational", supporting_intents: ["symptoms", "homa_ir", "clinical_context"], priority: "P0", publication_status: "draft", indexability: "not_public", must_link_to: ["hub_saude_metabolica", "hub_emagrecimento_obesidade", "agendamento"], should_receive_links_from: ["hub_saude_metabolica", "context_menopausa_composicao_metabolismo"], do_not_compete_with: ["sintomas_resistencia_insulina_separado", "homa_ir_separado"], conversion_goal: "appointment_start", cta_id: "cta_spoke_resistencia_agendamento", schema_type: "Article", credential_status: "pending_verification", review_status: "review_required", medical_review_status: "pending", regulatory_check_status: "pending", source_refs: strategicRefs },
  { page_id: "page_menopausa_composicao_metabolismo", content_node_id: "context_menopausa_composicao_metabolismo", silo_id: "silo_contextos_estrategicos", hub_id: null, page_type: "strategic_context", internal_title: "Menopausa / composicao / metabolismo", canonical_topic: "Menopausa e climaterio sob recorte de peso, composicao corporal e saude metabolica", slug: "/menopausa-composicao-metabolismo/", parent: "home", primary_intent: "informational_commercial", supporting_intents: ["body_composition", "metabolic_health", "weight_context"], priority: "P1", publication_status: "draft", indexability: "not_public", must_link_to: ["hub_composicao_corporal", "hub_saude_metabolica", "hub_emagrecimento_obesidade", "agendamento"], should_receive_links_from: ["home", "hub_composicao_corporal", "hub_saude_metabolica"], do_not_compete_with: ["hold_saude_hormonal_generica"], conversion_goal: "appointment_start", cta_id: "cta_context_menopausa_agendamento", schema_type: "MedicalWebPage", credential_status: "pending_verification", review_status: "review_required", medical_review_status: "pending", regulatory_check_status: "pending", source_refs: strategicRefs },
  { page_id: "page_farmacoterapia_glp1", content_node_id: "context_farmacoterapia_glp1", silo_id: "silo_contextos_estrategicos", hub_id: "hub_emagrecimento_obesidade", page_type: "strategic_context", internal_title: "Farmacoterapia / GLP-1", canonical_topic: "Farmacoterapia da obesidade e GLP-1 em conteudo educativo condicionado a review", slug: "/farmacoterapia-obesidade-glp-1/", parent: "hub_emagrecimento_obesidade", primary_intent: "informational_investigational", supporting_intents: ["glp1_overview", "clinical_follow_up", "weight_regain"], priority: "P1", publication_status: "hold", indexability: "not_public", must_link_to: ["hub_emagrecimento_obesidade", "spoke_preservacao_muscular", "spoke_reganho_manutencao"], should_receive_links_from: ["hub_emagrecimento_obesidade"], do_not_compete_with: ["hold_semaglutida_isolada", "hold_tirzepatida_isolada", "hold_comparativos_farmacologicos"], conversion_goal: "appointment_start", cta_id: "cta_context_glp1_agendamento", schema_type: "MedicalWebPage", credential_status: "pending_verification", review_status: "review_required", medical_review_status: "pending", regulatory_check_status: "pending", source_refs: strategicRefs },
  { page_id: "hold_nutrologia_titulo_landing", content_node_id: "hold_nutrologia_titulo_landing", silo_id: "silo_hold_regulatorio", hub_id: null, page_type: "institutional", internal_title: "Nutrologia como titulo/landing publica", canonical_topic: "Uso publico de Nutrologia condicionado a CRM/RQE", slug: "/hold/nutrologia/", parent: "home", primary_intent: "hold_credential", supporting_intents: ["local_transactional"], priority: "HOLD", publication_status: "hold", indexability: "not_public", must_link_to: [], should_receive_links_from: [], do_not_compete_with: ["sobre", "hub_emagrecimento_obesidade"], conversion_goal: null, cta_id: null, schema_type: "None", credential_status: "hold", review_status: "hold", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: holdRefs },
  { page_id: "hold_local_joao_pessoa", content_node_id: "local_joao_pessoa", silo_id: "silo_hold_local", hub_id: null, page_type: "institutional", internal_title: "Joao Pessoa local", canonical_topic: "Pagina local Joao Pessoa condicionada a operacao verificada", slug: "/hold/joao-pessoa/", parent: "home", primary_intent: "hold_local_transactional", supporting_intents: ["local_seo"], priority: "HOLD", publication_status: "hold", indexability: "not_public", must_link_to: [], should_receive_links_from: [], do_not_compete_with: ["agendamento"], conversion_goal: null, cta_id: null, schema_type: "None", credential_status: "hold", review_status: "hold", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: holdRefs },
  { page_id: "hold_local_campina_grande", content_node_id: "local_campina_grande", silo_id: "silo_hold_local", hub_id: null, page_type: "institutional", internal_title: "Campina Grande local", canonical_topic: "Pagina local Campina Grande condicionada a operacao verificada", slug: "/hold/campina-grande/", parent: "home", primary_intent: "hold_local_transactional", supporting_intents: ["local_seo"], priority: "HOLD", publication_status: "hold", indexability: "not_public", must_link_to: [], should_receive_links_from: [], do_not_compete_with: ["agendamento"], conversion_goal: null, cta_id: null, schema_type: "None", credential_status: "hold", review_status: "hold", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: holdRefs },
  { page_id: "hold_semaglutida_isolada", content_node_id: "hold_semaglutida_isolada", silo_id: "silo_hold_ymyl", hub_id: "hub_emagrecimento_obesidade", page_type: "spoke", internal_title: "Semaglutida isolada", canonical_topic: "Semaglutida isolada mantida fora da primeira onda", slug: "/hold/semaglutida/", parent: "context_farmacoterapia_glp1", primary_intent: "hold_ymyl", supporting_intents: ["drug_specific"], priority: "HOLD", publication_status: "hold", indexability: "not_public", must_link_to: [], should_receive_links_from: [], do_not_compete_with: ["context_farmacoterapia_glp1"], conversion_goal: null, cta_id: null, schema_type: "None", credential_status: "pending_verification", review_status: "hold", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: holdRefs },
  { page_id: "hold_tirzepatida_isolada", content_node_id: "hold_tirzepatida_isolada", silo_id: "silo_hold_ymyl", hub_id: "hub_emagrecimento_obesidade", page_type: "spoke", internal_title: "Tirzepatida isolada", canonical_topic: "Tirzepatida isolada mantida fora da primeira onda", slug: "/hold/tirzepatida/", parent: "context_farmacoterapia_glp1", primary_intent: "hold_ymyl", supporting_intents: ["drug_specific"], priority: "HOLD", publication_status: "hold", indexability: "not_public", must_link_to: [], should_receive_links_from: [], do_not_compete_with: ["context_farmacoterapia_glp1"], conversion_goal: null, cta_id: null, schema_type: "None", credential_status: "pending_verification", review_status: "hold", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: holdRefs },
  { page_id: "hold_comparativos_farmacologicos", content_node_id: "hold_comparativos_farmacologicos", silo_id: "silo_hold_ymyl", hub_id: "hub_emagrecimento_obesidade", page_type: "spoke", internal_title: "Comparativos farmacologicos", canonical_topic: "Comparativos farmacologicos fora da primeira onda", slug: "/hold/comparativos-farmacologicos/", parent: "context_farmacoterapia_glp1", primary_intent: "hold_ymyl", supporting_intents: ["drug_comparison"], priority: "HOLD", publication_status: "hold", indexability: "not_public", must_link_to: [], should_receive_links_from: [], do_not_compete_with: ["context_farmacoterapia_glp1"], conversion_goal: null, cta_id: null, schema_type: "None", credential_status: "pending_verification", review_status: "hold", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: holdRefs },
  { page_id: "hold_lipedema_core", content_node_id: "hold_lipedema_core", silo_id: "silo_hold_clinico", hub_id: null, page_type: "hub", internal_title: "Lipedema como core", canonical_topic: "Lipedema mantido separado de emagrecimento", slug: "/hold/lipedema/", parent: "home", primary_intent: "hold_clinical_scope", supporting_intents: ["specialist_search"], priority: "HOLD", publication_status: "hold", indexability: "not_public", must_link_to: [], should_receive_links_from: [], do_not_compete_with: ["hub_emagrecimento_obesidade"], conversion_goal: null, cta_id: null, schema_type: "None", credential_status: "pending_verification", review_status: "hold", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: holdRefs },
  { page_id: "hold_saude_hormonal_generica", content_node_id: "hold_saude_hormonal_generica", silo_id: "silo_hold_clinico", hub_id: null, page_type: "hub", internal_title: "Saude hormonal generica", canonical_topic: "Saude hormonal generica fora do escopo aprovado", slug: "/hold/saude-hormonal/", parent: "home", primary_intent: "hold_scope", supporting_intents: ["hormonal_health"], priority: "HOLD", publication_status: "hold", indexability: "not_public", must_link_to: [], should_receive_links_from: [], do_not_compete_with: ["context_menopausa_composicao_metabolismo"], conversion_goal: null, cta_id: null, schema_type: "None", credential_status: "pending_verification", review_status: "hold", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: holdRefs },
  { page_id: "hold_suplementacao_hub", content_node_id: "hold_suplementacao_hub", silo_id: "silo_hold_editorial", hub_id: null, page_type: "hub", internal_title: "Suplementacao como hub", canonical_topic: "Suplementacao como suporte editorial, nao hub", slug: "/hold/suplementacao/", parent: "home", primary_intent: "hold_editorial_scope", supporting_intents: ["protein", "creatine"], priority: "HOLD", publication_status: "hold", indexability: "not_public", must_link_to: [], should_receive_links_from: [], do_not_compete_with: ["hub_composicao_corporal"], conversion_goal: null, cta_id: null, schema_type: "None", credential_status: "pending_verification", review_status: "hold", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: holdRefs },
  { page_id: "hold_longevidade_hub", content_node_id: "hold_longevidade_hub", silo_id: "silo_hold_editorial", hub_id: null, page_type: "hub", internal_title: "Longevidade como hub", canonical_topic: "Longevidade generica fora da arquitetura inicial", slug: "/hold/longevidade/", parent: "home", primary_intent: "hold_editorial_scope", supporting_intents: ["prevention"], priority: "HOLD", publication_status: "hold", indexability: "not_public", must_link_to: [], should_receive_links_from: [], do_not_compete_with: ["hub_saude_metabolica"], conversion_goal: null, cta_id: null, schema_type: "None", credential_status: "pending_verification", review_status: "hold", medical_review_status: "not_applicable", regulatory_check_status: "not_applicable", source_refs: holdRefs },
] satisfies DraGermaniaPublicWebsiteContentNode[]

export type DraGermaniaPublicWebsiteContentNodeId = (typeof draGermaniaPublicWebsiteContentNodes)[number]["content_node_id"]
