-- Polished client-facing copy for the Germania discovery flow.
-- Keeps the strategic question keys/contract intact while making the experience lighter and more conversational.

update public.discovery_projects
set metadata = metadata || jsonb_build_object(
  'chapter_intros', jsonb_build_object(
    'identidade', jsonb_build_object('title','Sua história','intro','Esse bloco vai nos ajudar a entender quem você é além do currículo — os momentos, escolhas e valores que construíram sua forma de trabalhar.'),
    'pratica', jsonb_build_object('title','Seu jeito de cuidar','intro','Agora queremos entender como seu trabalho acontece na prática: o que você oferece, como acompanha seus pacientes e o que torna sua forma de cuidar diferente.'),
    'paciente', jsonb_build_object('title','Quem chega até você','intro','Esse bloco vai nos ajudar a compreender melhor seus pacientes: o que eles estão vivendo, o que já tentaram e o que precisam sentir antes de confiar em você.'),
    'autoridade', jsonb_build_object('title','Os assuntos que têm a sua assinatura','intro','Aqui vamos identificar os temas que mais combinam com sua experiência e que podem, ao longo do tempo, fortalecer seu nome na internet.'),
    'perguntas_reais', jsonb_build_object('title','As perguntas que seus pacientes realmente fazem','intro','Esse bloco é muito importante. As dúvidas que aparecem no consultório, no WhatsApp e nos retornos podem virar conteúdos úteis para outras pessoas que estão procurando exatamente essas respostas.'),
    'comercial', jsonb_build_object('title','O que você quer fortalecer','intro','Agora queremos entender quais partes do seu trabalho merecem mais atenção nos próximos meses. Isso nos ajuda a construir um site bonito, mas também útil para seus objetivos.'),
    'marca', jsonb_build_object('title','Como você quer ser percebida','intro','Esse bloco vai nos ajudar a encontrar o tom visual e emocional certo — o que deve aparecer quando alguém olha para sua marca e o que definitivamente não combina com você.'),
    'site', jsonb_build_object('title','O papel do novo site','intro','Aqui vamos definir o que o site precisa fazer por você: que sensação deve causar, que dúvidas deve resolver e qual deve ser o próximo passo de quem chega até ele.'),
    'acervo', jsonb_build_object('title','O que já temos em mãos','intro','Agora queremos entender quais fotos, vídeos, materiais e conteúdos já existem. Isso nos ajuda a aproveitar melhor o que você já construiu e identificar o que ainda precisamos produzir.'),
    'editorial', jsonb_build_object('title','Como o conteúdo pode continuar crescendo','intro','Esse bloco vai nos ajudar a construir uma rotina de conteúdo que respeite sua voz, sua autoridade e o nível de participação que você deseja ter.'),
    'fechamento', jsonb_build_object('title','Para fechar','intro','Queremos olhar um pouco para frente. As próximas respostas vão nos ajudar a entender o que faria esse projeto ser realmente valioso para você.')
  )
)
where slug = 'germania-bandeira';

update public.discovery_questions set prompt='Se você tivesse que contar sua trajetória profissional em poucos minutos, quais momentos foram mais importantes para chegar até aqui?', help_text='Não precisa organizar como um currículo. Queremos entender os momentos que mais marcaram sua história.' where template_key='germania-bandeira-v1' and question_key='trajetoria_resumo';
update public.discovery_questions set prompt='Teve algum momento que mudou a forma como você enxerga seu trabalho ou cuida dos seus pacientes?', help_text=null where template_key='germania-bandeira-v1' and question_key='virada_carreira';
update public.discovery_questions set prompt='O que é inegociável para você na forma de cuidar dos seus pacientes?', help_text='Pode falar de valores, postura, atenção, escuta, acompanhamento ou qualquer princípio que faça parte do seu jeito de trabalhar.' where template_key='germania-bandeira-v1' and question_key='crencas_profissionais';
update public.discovery_questions set prompt='Quando alguém conhece você pela primeira vez, como você gostaria de ser percebida?', help_text='Escolha as palavras que mais combinam com a imagem que você quer transmitir.' where template_key='germania-bandeira-v1' and question_key='percepcao_desejada';
update public.discovery_questions set prompt='Dessas características, quais duas precisam aparecer com mais força — e por quê?' where template_key='germania-bandeira-v1' and question_key='percepcao_prioritaria';
update public.discovery_questions set prompt='Quais formações, títulos, especializações ou experiências ajudam a contar sua trajetória profissional?', help_text='Pode incluir cursos, certificações, sociedades médicas, congressos, publicações, entrevistas ou outras experiências importantes.' where template_key='germania-bandeira-v1' and question_key='credenciais';
update public.discovery_questions set prompt='Hoje, quais são os principais motivos que levam uma pessoa a procurar você?' where template_key='germania-bandeira-v1' and question_key='motivos_consulta';
update public.discovery_questions set prompt='Quais tipos de pacientes ou casos você mais gosta de acompanhar e gostaria de receber com mais frequência?' where template_key='germania-bandeira-v1' and question_key='casos_prioritarios';
update public.discovery_questions set prompt='Existe algum tipo de demanda que aparece bastante, mas não representa o caminho que você quer fortalecer?' where template_key='germania-bandeira-v1' and question_key='casos_nao_prioritarios';
update public.discovery_questions set prompt='Quais tipos de consulta, acompanhamento ou serviço você oferece hoje?', help_text='Inclua também atendimentos online, programas, protocolos ou formatos especiais, se existirem.' where template_key='germania-bandeira-v1' and question_key='servicos_atuais';
update public.discovery_questions set prompt='O que costuma surpreender positivamente seus pacientes durante a consulta ou o acompanhamento?' where template_key='germania-bandeira-v1' and question_key='diferencial_consulta';
update public.discovery_questions set prompt='O que você gostaria de ver crescer no seu trabalho nos próximos meses ou anos?' where template_key='germania-bandeira-v1' and question_key='prioridade_crescimento';
update public.discovery_questions set prompt='Se você pudesse descrever o paciente que mais combina com o seu trabalho hoje, como ele seria?', help_text='Pense no momento de vida, rotina, necessidades e no tipo de relação que costuma funcionar melhor.' where template_key='germania-bandeira-v1' and question_key='perfil_paciente';
update public.discovery_questions set prompt='O que normalmente acontece para essa pessoa decidir: “agora eu preciso procurar ajuda”?' where template_key='germania-bandeira-v1' and question_key='gatilho_busca';
update public.discovery_questions set prompt='O que esse paciente geralmente já tentou antes de chegar até você — e o que costuma ter dado errado?' where template_key='germania-bandeira-v1' and question_key='frustracoes_previas';
update public.discovery_questions set prompt='Antes de marcar uma consulta, quais medos ou dúvidas aparecem com mais frequência?' where template_key='germania-bandeira-v1' and question_key='medos_objecoes';
update public.discovery_questions set prompt='Que palavras ou frases os pacientes usam para contar o que estão sentindo ou buscando?', help_text='Se conseguir, lembre da linguagem real que aparece no WhatsApp, no consultório ou no direct.' where template_key='germania-bandeira-v1' and question_key='linguagem_paciente';
update public.discovery_questions set prompt='Quais perguntas aparecem com mais frequência antes da consulta, principalmente no WhatsApp?' where template_key='germania-bandeira-v1' and question_key='perguntas_whatsapp';
update public.discovery_questions set prompt='Sobre quais assuntos você gostaria que as pessoas lembrassem de você?' where template_key='germania-bandeira-v1' and question_key='territorios_associacao';
update public.discovery_questions set prompt='Em quais temas você sente que tem mais experiência e segurança para falar hoje?' where template_key='germania-bandeira-v1' and question_key='temas_fortes';
update public.discovery_questions set prompt='Sobre quais assuntos você conseguiria conversar por horas sem cair no superficial?' where template_key='germania-bandeira-v1' and question_key='temas_horas';
update public.discovery_questions set prompt='Quais informações erradas, simplificações ou mitos você mais gostaria de corrigir?' where template_key='germania-bandeira-v1' and question_key='mitos_erros';
update public.discovery_questions set prompt='Daqui a dois anos, pelo que você gostaria de ser lembrada profissionalmente na internet?' where template_key='germania-bandeira-v1' and question_key='autoridade_2_anos';
update public.discovery_questions set prompt='Existe algum assunto ou tipo de abordagem que você prefere não associar à sua imagem?' where template_key='germania-bandeira-v1' and question_key='temas_evitar';
update public.discovery_questions set prompt='Quais são as perguntas que seus pacientes mais fazem no consultório, no WhatsApp ou nos retornos?', help_text='Pode escrever do jeito que eles realmente perguntam. Se conseguir, liste entre 10 e 30 dúvidas.' where template_key='germania-bandeira-v1' and question_key='duvidas_reais';
update public.discovery_questions set prompt='Tem alguma dúvida que parece simples, mas quase sempre abre espaço para uma conversa muito mais importante?' where template_key='germania-bandeira-v1' and question_key='duvidas_subestimadas';
update public.discovery_questions set prompt='Hoje, quais tipos de atendimento você mais gostaria de fortalecer?', help_text='Pode pensar tanto no que já funciona bem quanto no que você gostaria de ver crescer nos próximos meses.' where template_key='germania-bandeira-v1' and question_key='servicos_importantes';
update public.discovery_questions set prompt='Que tipo de paciente ou atendimento você gostaria que chegasse com mais frequência até você?' where template_key='germania-bandeira-v1' and question_key='crescer_demanda';
update public.discovery_questions set prompt='Existe alguma parte da sua agenda que já está no limite ou que você não gostaria de aumentar muito?' where template_key='germania-bandeira-v1' and question_key='capacidade_limitada';
update public.discovery_questions set prompt='Tem algum assunto que desperta muita curiosidade, mas raramente vira uma consulta?' where template_key='germania-bandeira-v1' and question_key='interesse_sem_resultado';
update public.discovery_questions set prompt='Quando alguém entra em contato, o que faz você perceber que aquela pessoa realmente combina com o seu trabalho?' where template_key='germania-bandeira-v1' and question_key='lead_qualificado';
update public.discovery_questions set prompt='Quais sensações ou estilos definitivamente não combinam com você?' where template_key='germania-bandeira-v1' and question_key='atributos_nao_desejados';
update public.discovery_questions set prompt='Que marcas, profissionais, sites, revistas, filmes, lugares ou universos visuais você acha bonitos e gostaria de usar como referência?' where template_key='germania-bandeira-v1' and question_key='referencias_visuais';
update public.discovery_questions set prompt='Se tiver links de sites, perfis ou referências que gosta, pode colocar aqui.' where template_key='germania-bandeira-v1' and question_key='referencias_links';
update public.discovery_questions set prompt='Se o novo site pudesse fazer uma coisa muito bem por você, qual seria a mais importante?' where template_key='germania-bandeira-v1' and question_key='objetivo_site';
update public.discovery_questions set prompt='Depois de conhecer você pelo site, qual deveria ser o próximo passo natural para essa pessoa?' where template_key='germania-bandeira-v1' and question_key='acao_principal';
update public.discovery_questions set prompt='O que alguém precisa entender sobre você ou sobre sua consulta antes de se sentir confortável para agendar?' where template_key='germania-bandeira-v1' and question_key='antes_de_agendar';
update public.discovery_questions set prompt='Imagine alguém chegando ao seu site sem conhecer você. O que essa pessoa deveria sentir, entender e fazer ao longo da visita?' where template_key='germania-bandeira-v1' and question_key='jornada_ideal';
update public.discovery_questions set prompt='Quais materiais você já tem e poderá compartilhar com a gente?' where template_key='germania-bandeira-v1' and question_key='materiais_disponiveis';
update public.discovery_questions set prompt='O que ainda não existe e provavelmente vamos precisar produzir para o projeto?' where template_key='germania-bandeira-v1' and question_key='materiais_faltantes';
update public.discovery_questions set prompt='Quais fontes, instituições, autores ou referências você considera confiáveis para apoiar conteúdos da sua área?' where template_key='germania-bandeira-v1' and question_key='fontes_confiaveis';
update public.discovery_questions set prompt='Como você gostaria de participar da revisão dos conteúdos antes de eles irem ao ar?' where template_key='germania-bandeira-v1' and question_key='revisao_conteudo';
update public.discovery_questions set prompt='Até onde você se sente confortável em deixar a inteligência artificial ajudar na produção dos conteúdos?' where template_key='germania-bandeira-v1' and question_key='autonomia_ia';
update public.discovery_questions set prompt='Que tipos de afirmação ou assunto você sempre gostaria de revisar pessoalmente antes da publicação?' where template_key='germania-bandeira-v1' and question_key='afirmacoes_revisao';
update public.discovery_questions set prompt='Existe algum tipo de promessa, linguagem ou assunto que você não quer ver no site ou nos conteúdos?' where template_key='germania-bandeira-v1' and question_key='temas_proibidos';
update public.discovery_questions set prompt='Pensando na sua rotina de verdade, qual frequência de novos conteúdos parece confortável para você?' where template_key='germania-bandeira-v1' and question_key='frequencia_editorial';
update public.discovery_questions set prompt='Daqui a um ano, o que precisaria ter acontecido para você olhar para esse projeto e pensar: “valeu muito a pena”?' where template_key='germania-bandeira-v1' and question_key='site_sucesso';
update public.discovery_questions set prompt='Tem alguma coisa importante sobre você, seu trabalho ou esse projeto que ainda não perguntamos?' where template_key='germania-bandeira-v1' and question_key='algo_nao_perguntado';